# Generated by Django 2.2.4 on 2020-05-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows_app', '0003_show_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='desc',
            field=models.TextField(),
        ),
    ]
